# Generated by Django 6.0 on 2025-12-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_houseplan_is_best_selling_alter_houseplan_is_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseplan',
            name='display_section',
            field=models.CharField(choices=[('house_plans', 'House Plans'), ('built_homes', 'Built Homes')], default='house_plans', help_text='Where this house plan will be displayed', max_length=20),
        ),
    ]
